export const LOADING_REGISTER = 'LOADING_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const ERROR_DISMISS_REGISTER = 'ERROR_DISMISS_REGISTER';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const REMOVE_USER_REGISTER_DATA = 'REMOVE_USER_REGISTER_DATA';
export const SET_REGISTERED_SUCCESSFULLY = 'SET_REGISTERED_SUCCESSFULLY';